#ifndef TAKEN_KEYDEFINES_INCLUDED
#define TAKEN_KEYDEFINES_INCLUDED

#define FORWARD_PASS defined(UNITY_PASS_FORWARDBASE)

#define ADDITIVE_PASS defined(UNITY_PASS_FORWARDADD)

#define SHADOW_PASS defined(UNITY_PASS_SHADOWCASTER)

#define OUTLINE_PASS defined(OUTLINE)

#define CUTOUT_ENABLED defined(_ALPHATEST_ON)

#define DITHER_ENABLED defined(_ALPHADITHER_ON)

#define FADE_ENABLED defined(_ALPHABLEND_ON)

#define TRANSPARENT_ENABLED defined(_ALPHAPREMULTIPLY_ON)

#define NON_OPAQUE_ENABLED defined(_ALPHATEST_ON) || defined(_ALPHADITHER_ON) || defined(_ALPHABLEND_ON) || defined(_ALPHAPREMULTIPLY_ON)

#define LIGHTING_ENABLED defined(_LIGHTING_ON)

#define REFLECTIONS_ENABLED defined(_REFLECTIONS_ON)

#define RIM_ENABLED defined(_RIM_ON)

#define GRADIENT_ENABLED defined(_GRADIENT_ON)

#define DISSOLVE_ENABLED defined(_DISSOLVE_ON)

#define PATCHES_ENABLED defined(_PATCHES_ON)

#define OUTLINE_INVERT_ENABLED defined(_OUTLINE_INVERT_ON)

#endif // TAKEN_KEYDEFINES_INCLUDED